name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        apt-get update
        apt-get install libpcap-dev zlib1g-dev libpcre3 libpcre3-dev
        make
        find . -type f
